### ISSUE TITLE
[ENH]Hype Track: Turn off track when combat has ended

### ISSUE THREAD

**Issue by Rawrly85** [death-save/maestro#38] opened 2020-02-28 18:43 UTC
Currently, the hype track music keeps playing unless you manually stop the track. It be nice if it turns off once the combat was ended.

**Comment by mikejstan** [comment] 2020-04-09 16:11
Can we have an option to fade out track when combat ends?

**Comment by eclarke12** [comment] 2020-06-06 04:54
Duplicate of #36

**Closed by eclarke12** 2020-06-06 04:54 UTC
Labels: enhancement
