### ISSUE TITLE
When Combat Ends, End Hype Tracks

### ISSUE THREAD

**Issue by Nuku** [death-save/maestro#129] opened 2021-07-13 14:51 UTC
Currently, if a hype track is going and combat ends, it continues.

Ideally, when you end combat, all things relating to ending a turn should trigger, which would end the song, and resume other noises if they were being quieted.

**Comment by eclarke12** [comment] 2021-10-03 19:01
Fixed in upcoming release

**Comment by Nuku** [comment] 2021-10-03 19:03
Woo! Thank you.

**Comment by eclarke12** [comment] 2021-10-03 19:11
Duplicate of #36

**Closed by eclarke12** 2021-10-03 19:11 UTC
Labels: enhancement
