### ISSUE TITLE
Maestro causes congestion troubles on the whole app

### ISSUE THREAD

**Issue by Angor-de-Redjak** [death-save/maestro#105] opened 2021-02-01 01:05 UTC
**Describe the bug**
Sometimes when a playlist is read and it ends, it causes some kind of lag for the whole app. Buttons doesn't answer, can't scroll the map etc.
It requires a few minutes or to refresh the app to regain control of functionnalities.

**To Reproduce**
1. Play a playlist with some musics in it
2. Let music run for about 30 minutes (can switch playlist)

**Expected behavior**
As said above, the whole software begins to freeze. Music stops (but bug is always triggered at the end of a song), can't scroll the map, click on the menu or buttons etc.
After a few minutes or F5, music starts again as all the other things.

**Foundry Setup (please complete the following information):**
 - OS: Windows 7
 - Browser Electron App
 - Foundry Version 0.7.9
 - Maestro Version 0.7.2

**Additional context**
I had this problem since 4 months now and it was a real pain. I finally found the culprit using the culprit module. I have done a whole game without having congestions confirming that my problem came from Maestro.
 I can also assure that it doesn't come from my connexion.
 
 If you need diagnostics or more details, feel free to ask!

**Comment by eclarke12** [comment] 2021-02-01 02:24
duplicate of #96 (and others)
fixed in v073

**Closed by eclarke12** 2021-02-01 02:24 UTC
Labels: bug, duplicate
