### ISSUE TITLE
Add an option to pause any playlist on combat start.

### ISSUE THREAD

**Issue by SalieriC** [death-save/maestro#75] opened 2020-08-06 12:11 UTC
I like having a playlist on at all times, when combat starts this leads to two playlists being active at the same time. An option to pause the active plalist when a combat starts and to resume when it ends would be great.

**Comment by eclarke12** [comment] 2020-09-08 22:24
related/duplicate of #69

**Comment by eclarke12** [comment] 2020-10-31 22:30
closing this. will capture in #69

**Closed by eclarke12** 2020-10-31 22:30 UTC
Labels: enhancement
